repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0            # use the latest stable release
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0            # match your project’s Python version
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --in-place

  - repo: local
    hooks:
      - id: flake8
        name: flake8 (local)
        entry: flake8
        language: system
        types: [python]
        args: ["--max-line-length=88"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.2
    hooks:
      - id: pylint
