runtime: python39  # Use the latest stable Python 3.9 runtime

entrypoint: gunicorn -b :$PORT app:app  # Use gunicorn to run the Flask app

handlers:
  - url: /webhook  # This maps to your webhook route
    script: auto  # Tells GAE to route to your app's entry point (Flask app)

automatic_scaling:
  min_instances: 1  # Ensure that at least one instance is always running
  max_instances: 3  # You can set the max number of instances based on expected traffic

network:
  instance_tag: "line-bot-instance"  # Add this tag if you want to add custom network configuration later (optional)