runtime: python39

# Tell App Engine how to start your app:
entrypoint: gunicorn -b :$PORT app:app

# If you need more memory/CPU you can bump this to F2 or higher
instance_class: F1

env_variables:
  # LINE Bot credentials

  # MQTT Broker Settings
  MQTT_BROKER:   "d8e42404.ala.asia-southeast1.emqxsl.com"
  MQTT_PORT:     "8883"
  MQTT_TOPIC:    "garage/command"

  # Location geofence parameters
  PARK_LAT:      "24.190502"
  PARK_LNG:      "120.6686369"
  MAX_DIST_KM:   "0.5"

  # Timeouts & token TTLs (in seconds)
  VERIFY_TTL:    "300"
  LOCATION_TTL:  "10"

  # HTTP port (must match gunicorn bind)
  PORT:          "8080"

  # Base URL for the verify-page link
  VERIFY_URL_BASE: "https://linebot-458714.appspot.com/static/verify.html"

  # Security / Rate limiting
  RATE_LIMIT_ENABLED:     "true"
  MAX_REQUESTS_PER_MINUTE: "30"

  # Secrets backend choice
  SECRETS_BACKEND: "gcp"

  # (Only used if SECRETS_BACKEND=gcp)
  GOOGLE_CLOUD_PROJECT: "linebot-458714"

  # Logging dir
  LOG_DIR: "/tmp"

  # Cloud Storage persistence settings
  DB_BUCKET:    "my-linebot-assets"
  DB_FILENAME:  "users.db"
  CRT_BUCKET:   "my-linebot-assets"
  CRT_FILENAME: "emqxsl-ca.crt"

# Serve anything under /static directly
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
