runtime: python39  # Use the latest stable Python 3.9 runtime

entrypoint: gunicorn -b :$PORT app:app  # Use gunicorn to run the Flask app

env_variables:
  LINE_CHANNEL_ACCESS_TOKEN: "I6l46sYem5H4kuRx/J14iT64aNNTxSvOaSQzD3Wsp5U+tN/yjMM/mbq2H74zn6Jjo/cpiPfIaUAnV8sMsO4UnhNetrUZxLpC9SK8fIR4hSRomSJ3H4wr+y0GXcr+uBIiKjdnzi0jKE7+K4gzXYvIRQdB04t89/1O/w1cDnyilFU="
  LINE_CHANNEL_SECRET: "2eeb33ec876a3a3ad7cba129de6d3207"
  # Add other environment variables if necessary, such as for database connections or API keys

handlers:
  - url: /webhook  # This maps to your webhook route
    script: auto  # Tells GAE to route to your app's entry point (Flask app)
  - url: /static  # Serves static files like CSS, JS, or images from the 'static' folder
    static_dir: static/  # You can serve static content from a directory

automatic_scaling:
  min_instances: 1  # Ensure that at least one instance is always running
  max_instances: 3  # You can set the max number of instances based on expected traffic

network:
  instance_tag: "line-bot-instance"  # Add this tag if you want to add custom network configuration later (optional)