runtime: python311

# Tell App Engine how to start your app:
entrypoint: gunicorn -b :$PORT app:app

# If you need more memory/CPU you can bump this to F2 or higher
instance_class: F1

# Automatic scaling configuration
automatic_scaling:
  max_instances: 10
  min_instances: 0

env_variables:
  # LINE Bot credentials

  # MQTT Broker Settings
  MQTT_BROKER:   "d8e42404.ala.asia-southeast1.emqxsl.com"
  MQTT_PORT:     "8883"
  MQTT_TOPIC:    "garage/command"

  # Location geofence parameters 24.18590° N, 120.68247° E
  PARK_LAT:      "24.19092"
  PARK_LNG:      "120.66806"
  MAX_DIST_KM:   "0.5"

  # Timeouts & token TTLs (in seconds)
  VERIFY_TTL:    "300"
  LOCATION_TTL:  "60"

  # HTTP port (must match gunicorn bind)
  PORT:          "8080"

  # Base URL for the verify-page link
  VERIFY_URL_BASE: "https://line-462014.appspot.com/static/verify.html"

  # Security / Rate limiting
  RATE_LIMIT_ENABLED:     "true"
  MAX_REQUESTS_PER_MINUTE: "30"

  # Debug Mode (FOR TESTING ONLY - disable in production)
  DEBUG_MODE: "true"
  DEBUG_USER_IDS: "Uea6813ef8ec77e7446090621ebcf472a,U1d640cea545510e631396b5306ade151,U82a11186c98448e8c2f8f9ee9145ffdc"

  # Secrets backend choice
  SECRETS_BACKEND: "gcp"

  # (Only used if SECRETS_BACKEND=gcp)
  GOOGLE_CLOUD_PROJECT: "line-462014"

  # Logging dir
  LOG_DIR: "/tmp"

  # Cloud Storage persistence settings
  DB_BUCKET:    "line-bot-assets"
  DB_FILENAME:  "users.db"
  CRT_BUCKET:   "line-bot-assets"
  CRT_FILENAME: "emqxsl-ca.crt"

  # Database Settings
  # MONGO_URI: "mongodb+srv://username:password@cluster.mongodb.net/?retryWrites=true&w=majority"
  # DB_MODE: "mongo"  # Options: "mongo" (use MongoDB), "sqlite" (use SQLite), "auto" (try MongoDB, fallback to SQLite)

# Serve anything under /static directly
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
